# Data
For this project, we use three datasets that provide insights into different aspects of restaurant and food-related data.

## Description
1. Restaurant Inspection Data

We utilize the [DOHMH New York City Restaurant Inspection dataset](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data) from the NYC OpenData library. This dataset includes details on all sustained or pending violation citations from full or special program inspections conducted within three years prior to the most recent inspection. The data covers restaurants and college cafeterias that are actively operating as of the RECORD DATE (the date the data was pulled).

Key points about this dataset:
	- This is a huge data set containing about 260,000 observations of 27 variables. The data is updated daily according to the description of the data.
	- Each violation record is associated with an inspection, and establishments with multiple violations will have repeated fields for each violation.
	- Establishments are uniquely identified by their CAMIS (record ID) number.
	- Restaurants that have started operations or gone out of business within the dataset period are included only if they were active on the RECORD DATE.
	- Records also include restaurants applying for permits but not yet inspected and inspections resulting in no violations.
	- Restaurants with an inspection date of “1/1/1900” are new establishments awaiting inspection.
	- Restaurants with no violations are represented by a single row coded as having no violations in the ACTION field.

2. Fast Food Chain Analysis Data

For the analysis of the most popular fast food chains, we use a dataset that provides nationwide data for the United States, not limited to New York. This dataset is sourced from [Passby Blog’s Top Fast Food Chains Foot Traffic](https://passby.com/blog/top-fast-food-chains-foot-traffic/), offering insights into consumer behavior and fast food chain popularity across the country.

3. Customer Satisfaction Data

To explore customer satisfaction, we use data from the [American Customer Satisfaction Index (ACSI)](https://theacsi.org/industries/restaurant/food-delivery/). This dataset evaluates customer satisfaction levels across various restaurant types and food delivery services, providing valuable insights into consumer preferences and trends.

## Missing value analysis

For the first dataset, the process includes:
1. Remove key feature missing including restaurant names, inspect date, and grade.
2. Change categorical variables into factors for visualization.
(3. Create additional features for analysis.)

